### ISSUE TITLE
Lỗi validate khi đăng kí !

### ISSUE THREAD

**Issue by ninhnguyen1994** [leeking29081994/nongsan#2]
Tất cả các validate đều hiển thị là tiếng việt nhưng có 1 chỗ là tiếng anh !
<img width="1409" alt="Screen Shot 2022-01-09 at 08 41 59" src="https://user-images.githubusercontent.com/93476453/148663737-da336991-4175-4a4b-9a85-389d049a4f9d.png">

**Comment by Chihero95** [comment]
(Chi's comment) someone fixed it!

**Comment by Chihero95** [comment]
Đã check và không thấy còn lỗi gì
![image](https://user-images.githubusercontent.com/93476211/150647689-6ef70c62-f931-4201-9892-9c3e744ad475.png)

**Comment by ninhnguyen1994** [comment]
ok em !
